apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchlist-deployment
  labels:
    app: watchlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchlist
  template:
    metadata:
      labels:
        app: watchlist
    spec:
      containers:
      - name: watchlist
        image: pkar15/watchlistapp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: watchlist-service
  labels:
    app: watchlist
spec:
  selector:
    app: watchlist
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
